### ISSUE TITLE
issue for surrogate data testing

### ISSUE THREAD

**Issue by anny9936** [PhysLancIT/LancsBioMed#1]
In the subfile of Surrogate_Data_Testing, 

the signal embedding script requires boxdim.m and corrdim.m

however, none of them can be found in the toolbox file.

Could you please tell me where can I find the corresponding functions?

Thanks for sharing the toolbox and code.

Best,

**Comment by PhysLancIT** [comment]
[Surrogate Data Addin.zip](https://github.com/PhysLancIT/LancsBioMed/files/4830325/Surrogate.Data.Addin.zip)

From the toolbox development team
" The surrogate codes are set up to automatically calculate embedding dimension and thus these two codes should not be required to calculate any of the surrogates. If you require more control over the embedding, attached are the codes written by Dima Iatsenko."
